-- Create daily_usage table for rate limiting
create table if not exists daily_usage (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  date date not null,
  msg_count int default 0,
  unique (user_id, date)
);

-- Enable Row Level Security (RLS)
alter table daily_usage enable row level security;

-- Policies

-- 1. Users can view their own usage
create policy "Users can view their own usage"
on daily_usage for select
using (auth.uid() = user_id);

-- 2. Users can update their own usage (increment count)
create policy "Users can update their own usage"
on daily_usage for update
using (auth.uid() = user_id);

-- 3. Users can insert their own usage (first message of the day)
create policy "Users can insert their own usage"
on daily_usage for insert
with check (auth.uid() = user_id);
